-- ============================================================
-- Normalizar nombres de ciudad en rutas (origen y destino)
-- para que coincidan exactamente con el catálogo mexico-cities.ts
-- ============================================================

-- ── Helpers: actualizar origen ──────────────────────────────
UPDATE "routes" SET "origin" = 'Acámbaro'            WHERE lower("origin") = 'acambaro';
UPDATE "routes" SET "origin" = 'Acaponeta'           WHERE lower("origin") = 'acaponeta';
UPDATE "routes" SET "origin" = 'Aguascalientes'      WHERE lower("origin") = 'aguascalientes';
UPDATE "routes" SET "origin" = 'Cárdenas'            WHERE lower("origin") = 'cardenas';
UPDATE "routes" SET "origin" = 'Chalco'              WHERE lower("origin") = 'chalco';
UPDATE "routes" SET "origin" = 'Chihuahua'           WHERE lower("origin") = 'chiuahua';
UPDATE "routes" SET "origin" = 'Ciudad Juárez'       WHERE lower("origin") = 'ciudad juarez';
UPDATE "routes" SET "origin" = 'Coatzacoalcos'       WHERE lower("origin") = 'coatzacoalcos';
UPDATE "routes" SET "origin" = 'Comalcalco'          WHERE lower("origin") = 'comalcalco';
UPDATE "routes" SET "origin" = 'Comitán de Domínguez' WHERE lower("origin") = 'comitan';
UPDATE "routes" SET "origin" = 'Cuautitlán'          WHERE lower("origin") = 'cuautitlan';
UPDATE "routes" SET "origin" = 'Cuautla'             WHERE lower("origin") = 'cuautla';
UPDATE "routes" SET "origin" = 'Cuernavaca'          WHERE lower("origin") = 'cuernavaca';
UPDATE "routes" SET "origin" = 'Culiacán'            WHERE lower("origin") = 'culiacan';
UPDATE "routes" SET "origin" = 'Frontera Comalapa'   WHERE lower("origin") = 'frontera comala';
UPDATE "routes" SET "origin" = 'Guadalajara'         WHERE lower("origin") = 'guadalajara';
UPDATE "routes" SET "origin" = 'Guasave'             WHERE lower("origin") = 'guasave';
UPDATE "routes" SET "origin" = 'Gustavo A. Madero'   WHERE lower("origin") = 'gustavo a mader';
UPDATE "routes" SET "origin" = 'Heroica Ciudad de Huajuapan de León' WHERE lower("origin") = 'huajuapan';
UPDATE "routes" SET "origin" = 'Huetamo'             WHERE lower("origin") = 'huetamo';
UPDATE "routes" SET "origin" = 'Huixtla'             WHERE lower("origin") = 'huixtla';
UPDATE "routes" SET "origin" = 'Iztapalapa'          WHERE lower("origin") = 'iztapalapa';
UPDATE "routes" SET "origin" = 'Jacona'              WHERE lower("origin") = 'jacona';
UPDATE "routes" SET "origin" = 'Jalapa'              WHERE lower("origin") = 'jalapa';
UPDATE "routes" SET "origin" = 'Juchitán'            WHERE lower("origin") = 'juchitan';
UPDATE "routes" SET "origin" = 'La Barca'            WHERE lower("origin") = 'la barca';
UPDATE "routes" SET "origin" = 'Las Choapas'         WHERE lower("origin") = 'las choapas';
UPDATE "routes" SET "origin" = 'León'                WHERE lower("origin") = 'leon';
UPDATE "routes" SET "origin" = 'Lerdo de Tejada'     WHERE lower("origin") = 'lerdo de tejada';
UPDATE "routes" SET "origin" = 'Los Mochis'          WHERE lower("origin") = 'los mochis';
UPDATE "routes" SET "origin" = 'Los Reyes'           WHERE lower("origin") = 'los reyes';
UPDATE "routes" SET "origin" = 'Magdalena'           WHERE lower("origin") = 'magdalena';
UPDATE "routes" SET "origin" = 'Maravatío'           WHERE lower("origin") = 'maravatio';
UPDATE "routes" SET "origin" = 'Mazatlán'            WHERE lower("origin") = 'mazatlan';
UPDATE "routes" SET "origin" = 'Mexicali'            WHERE lower("origin") = 'mexicali';
UPDATE "routes" SET "origin" = 'Minatitlán'          WHERE lower("origin") = 'minatitlan';
UPDATE "routes" SET "origin" = 'Misantla'            WHERE lower("origin") = 'misantla';
UPDATE "routes" SET "origin" = 'Monterrey'           WHERE lower("origin") = 'monterrey';
UPDATE "routes" SET "origin" = 'Morelia'             WHERE lower("origin") = 'morelia';
UPDATE "routes" SET "origin" = 'Naucalpan de Juárez' WHERE lower("origin") = 'naucalpan';
UPDATE "routes" SET "origin" = 'Oaxaca de Juárez'    WHERE lower("origin") = 'oaxaca';
UPDATE "routes" SET "origin" = 'Ocosingo'            WHERE lower("origin") = 'ocosingo';
UPDATE "routes" SET "origin" = 'Piedras Negras'      WHERE lower("origin") = 'piedras negras';
UPDATE "routes" SET "origin" = 'Puebla'              WHERE lower("origin") = 'puebla';
UPDATE "routes" SET "origin" = 'Puerto Vallarta'     WHERE lower("origin") = 'puerto vallarta';
UPDATE "routes" SET "origin" = 'Sahuayo'             WHERE lower("origin") = 'sahuayo';
UPDATE "routes" SET "origin" = 'Santa Cruz de Juventino Rosas' WHERE lower("origin") = 'juventino rosas';
UPDATE "routes" SET "origin" = 'Sayula'              WHERE lower("origin") = 'sayula';
UPDATE "routes" SET "origin" = 'Tepeaca'             WHERE lower("origin") = 'tepeaca';
UPDATE "routes" SET "origin" = 'Tepic'               WHERE lower("origin") = 'tepic';
UPDATE "routes" SET "origin" = 'Tierra Blanca'       WHERE lower("origin") = 'tierra blanca';
UPDATE "routes" SET "origin" = 'Toluca'              WHERE lower("origin") = 'toluca';
UPDATE "routes" SET "origin" = 'Tonalá'              WHERE lower("origin") = 'tonala';
UPDATE "routes" SET "origin" = 'Uriangato'           WHERE lower("origin") = 'uriangato';
UPDATE "routes" SET "origin" = 'Veracruz'            WHERE lower("origin") = 'veracruz';
UPDATE "routes" SET "origin" = 'Zapopan'             WHERE lower("origin") = 'zapopan';

-- ── Actualizar destino + estado ─────────────────────────────
UPDATE "routes" SET "destination" = 'Acámbaro',            "destination_state" = 'Guanajuato'       WHERE lower("destination") = 'acambaro';
UPDATE "routes" SET "destination" = 'Acaponeta',           "destination_state" = 'Nayarit'          WHERE lower("destination") = 'acaponeta';
UPDATE "routes" SET "destination" = 'Aguascalientes',      "destination_state" = 'Aguascalientes'   WHERE lower("destination") = 'aguascalientes';
UPDATE "routes" SET "destination" = 'Cárdenas',            "destination_state" = 'Tabasco'          WHERE lower("destination") = 'cardenas';
UPDATE "routes" SET "destination" = 'Chalco',              "destination_state" = 'Estado de México' WHERE lower("destination") = 'chalco';
UPDATE "routes" SET "destination" = 'Chihuahua',           "destination_state" = 'Chihuahua'        WHERE lower("destination") = 'chiuahua';
UPDATE "routes" SET "destination" = 'Ciudad Juárez',       "destination_state" = 'Chihuahua'        WHERE lower("destination") = 'ciudad juarez';
UPDATE "routes" SET "destination" = 'Coatzacoalcos',       "destination_state" = 'Veracruz'         WHERE lower("destination") = 'coatzacoalcos';
UPDATE "routes" SET "destination" = 'Comalcalco',          "destination_state" = 'Tabasco'          WHERE lower("destination") = 'comalcalco';
UPDATE "routes" SET "destination" = 'Comitán de Domínguez',"destination_state" = 'Chiapas'          WHERE lower("destination") = 'comitan';
UPDATE "routes" SET "destination" = 'Cuautitlán',          "destination_state" = 'Estado de México' WHERE lower("destination") = 'cuautitlan';
UPDATE "routes" SET "destination" = 'Cuautla',             "destination_state" = 'Morelos'          WHERE lower("destination") = 'cuautla';
UPDATE "routes" SET "destination" = 'Cuernavaca',          "destination_state" = 'Morelos'          WHERE lower("destination") = 'cuernavaca';
UPDATE "routes" SET "destination" = 'Culiacán',            "destination_state" = 'Sinaloa'          WHERE lower("destination") = 'culiacan';
UPDATE "routes" SET "destination" = 'Frontera Comalapa',   "destination_state" = 'Chiapas'          WHERE lower("destination") = 'frontera comala';
UPDATE "routes" SET "destination" = 'Guadalajara',         "destination_state" = 'Jalisco'          WHERE lower("destination") = 'guadalajara';
UPDATE "routes" SET "destination" = 'Guasave',             "destination_state" = 'Sinaloa'          WHERE lower("destination") = 'guasave';
UPDATE "routes" SET "destination" = 'Gustavo A. Madero',   "destination_state" = 'Ciudad de México' WHERE lower("destination") = 'gustavo a mader';
UPDATE "routes" SET "destination" = 'Heroica Ciudad de Huajuapan de León', "destination_state" = 'Oaxaca' WHERE lower("destination") = 'huajuapan';
UPDATE "routes" SET "destination" = 'Huetamo',             "destination_state" = 'Michoacán'        WHERE lower("destination") = 'huetamo';
UPDATE "routes" SET "destination" = 'Huixtla',             "destination_state" = 'Chiapas'          WHERE lower("destination") = 'huixtla';
UPDATE "routes" SET "destination" = 'Iztapalapa',          "destination_state" = 'Ciudad de México' WHERE lower("destination") = 'iztapalapa';
UPDATE "routes" SET "destination" = 'Jacona',              "destination_state" = 'Michoacán'        WHERE lower("destination") = 'jacona';
UPDATE "routes" SET "destination" = 'Jalapa',              "destination_state" = 'Veracruz'         WHERE lower("destination") = 'jalapa';
UPDATE "routes" SET "destination" = 'Juchitán',            "destination_state" = 'Oaxaca'           WHERE lower("destination") = 'juchitan';
UPDATE "routes" SET "destination" = 'La Barca',            "destination_state" = 'Jalisco'          WHERE lower("destination") = 'la barca';
UPDATE "routes" SET "destination" = 'Las Choapas',         "destination_state" = 'Veracruz'         WHERE lower("destination") = 'las choapas';
UPDATE "routes" SET "destination" = 'León',                "destination_state" = 'Guanajuato'       WHERE lower("destination") = 'leon';
UPDATE "routes" SET "destination" = 'Lerdo de Tejada',     "destination_state" = 'Veracruz'         WHERE lower("destination") = 'lerdo de tejada';
UPDATE "routes" SET "destination" = 'Los Mochis',          "destination_state" = 'Sinaloa'          WHERE lower("destination") = 'los mochis';
UPDATE "routes" SET "destination" = 'Los Reyes',           "destination_state" = 'Michoacán'        WHERE lower("destination") = 'los reyes';
UPDATE "routes" SET "destination" = 'Magdalena',           "destination_state" = 'Jalisco'          WHERE lower("destination") = 'magdalena';
UPDATE "routes" SET "destination" = 'Maravatío',           "destination_state" = 'Michoacán'        WHERE lower("destination") = 'maravatio';
UPDATE "routes" SET "destination" = 'Mazatlán',            "destination_state" = 'Sinaloa'          WHERE lower("destination") = 'mazatlan';
UPDATE "routes" SET "destination" = 'Mexicali',            "destination_state" = 'Baja California'  WHERE lower("destination") = 'mexicali';
UPDATE "routes" SET "destination" = 'Minatitlán',          "destination_state" = 'Veracruz'         WHERE lower("destination") = 'minatitlan';
UPDATE "routes" SET "destination" = 'Misantla',            "destination_state" = 'Veracruz'         WHERE lower("destination") = 'misantla';
UPDATE "routes" SET "destination" = 'Monterrey',           "destination_state" = 'Nuevo León'       WHERE lower("destination") = 'monterrey';
UPDATE "routes" SET "destination" = 'Morelia',             "destination_state" = 'Michoacán'        WHERE lower("destination") = 'morelia';
UPDATE "routes" SET "destination" = 'Naucalpan de Juárez', "destination_state" = 'Estado de México' WHERE lower("destination") = 'naucalpan';
UPDATE "routes" SET "destination" = 'Oaxaca de Juárez',    "destination_state" = 'Oaxaca'           WHERE lower("destination") = 'oaxaca';
UPDATE "routes" SET "destination" = 'Ocosingo',            "destination_state" = 'Chiapas'          WHERE lower("destination") = 'ocosingo';
UPDATE "routes" SET "destination" = 'Piedras Negras',      "destination_state" = 'Veracruz'         WHERE lower("destination") = 'piedras negras';
UPDATE "routes" SET "destination" = 'Puebla',              "destination_state" = 'Puebla'           WHERE lower("destination") = 'puebla';
UPDATE "routes" SET "destination" = 'Puerto Vallarta',     "destination_state" = 'Jalisco'          WHERE lower("destination") = 'puerto vallarta';
UPDATE "routes" SET "destination" = 'Sahuayo',             "destination_state" = 'Michoacán'        WHERE lower("destination") = 'sahuayo';
UPDATE "routes" SET "destination" = 'Santa Cruz de Juventino Rosas', "destination_state" = 'Guanajuato' WHERE lower("destination") = 'juventino rosas';
UPDATE "routes" SET "destination" = 'Sayula',              "destination_state" = 'Jalisco'          WHERE lower("destination") = 'sayula';
UPDATE "routes" SET "destination" = 'Tepeaca',             "destination_state" = 'Puebla'           WHERE lower("destination") = 'tepeaca';
UPDATE "routes" SET "destination" = 'Tepic',               "destination_state" = 'Nayarit'          WHERE lower("destination") = 'tepic';
UPDATE "routes" SET "destination" = 'Tierra Blanca',       "destination_state" = 'Veracruz'         WHERE lower("destination") = 'tierra blanca';
UPDATE "routes" SET "destination" = 'Toluca',              "destination_state" = 'Estado de México' WHERE lower("destination") = 'toluca';
UPDATE "routes" SET "destination" = 'Tonalá',              "destination_state" = 'Jalisco'          WHERE lower("destination") = 'tonala';
UPDATE "routes" SET "destination" = 'Uriangato',           "destination_state" = 'Guanajuato'       WHERE lower("destination") = 'uriangato';
UPDATE "routes" SET "destination" = 'Veracruz',            "destination_state" = 'Veracruz'         WHERE lower("destination") = 'veracruz';
UPDATE "routes" SET "destination" = 'Zapopan',             "destination_state" = 'Jalisco'          WHERE lower("destination") = 'zapopan';
